name: zypay_flutter_sdk
description: A comprehensive Flutter SDK for blockchain payment processing with support for multiple blockchains including TON and BSC.
version: 1.0.3
homepage: https://github.com/zypay-dev/flutter-sdk
repository: https://github.com/zypay-dev/flutter-sdk.git
issue_tracker: https://github.com/zypay-dev/flutter-sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.5+1
  
  # Network & WebSocket
  socket_io_client: ^3.1.2
  http: ^1.5.0
  
  # UI & Animations
  qr_flutter: ^4.1.0
  flutter_svg: ^2.2.1
  
  # Utilities
  intl: ^0.20.2
  logger: ^2.6.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic

